{
 "title": "admins0008 - ICMP Targets",
 "description": "Blackbox exporter - ICMP https://github.com/prometheus/blackbox_exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(probe_icmp_duration_seconds{team=\"admins0008\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(probe_icmp_duration_seconds{job=~\"$job\",team=\"admins0008\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ICMP RTT",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(probe_icmp_duration_seconds{phase=\"rtt\",job=~\"$job\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ICMP packet loss",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "1-probe_success{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ICMP $instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "1-avg_over_time(probe_success{job=~\"$job\",instance=~\"$instance\"}[$__interval])",
     "legendFormat": "packet loss"
    },
    {
     "expr": "probe_icmp_duration_seconds{phase=\"rtt\",job=~\"$job\",instance=~\"$instance\"} > 0",
     "legendFormat": "RTT"
    }
   ]
  }
 ]
}