{
 "title": "server1 app1 API",
 "description": "from Grafana",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(probe_http_status_code{job=\"$blackbox_server1_rest_api\"},job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(probe_http_status_code{job=\"$job\"},instance)"
    }
   },
   {
    "name": "url",
    "query": {
     "query": "label_values(probe_http_status_code{instance=\"$instance\"},url)"
    }
   },
   {
    "name": "phase",
    "label": "HTTP phase",
    "query": {
     "query": "label_values(probe_http_duration_seconds{url=\"$url\"},phase)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Status Code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"$job\",url=~\"$url\"}",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"$job\",url=~\"$url\", job=\"blackbox_server1_rest_api\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"$job\",url=~\"$url\",job=\"blackbox_server1_rest_api\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_version{job=\"$job\",url=~\"$url\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "HTTP Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "status"
    }
   ]
  },
  {
   "title": "DNS Resolution from MK",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_dns_query_succeeded{job=\"blackbox_server1_rest_api\", instance=\"$instance\",dnsserver=\"10.10.10.10\"}",
     "legendFormat": "status"
    }
   ]
  },
  {
   "title": "DNS Resolution from ΚK",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_dns_query_succeeded{job=\"blackbox_server1_rest_api\", instance=\"$instance\",dnsserver=\"10.10.10.11\"}",
     "legendFormat": "status"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"$job\",url=~\"$url\"}",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{job=\"$job\",url=~\"$url\"}) by (url)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{job=\"$job\",url=~\"$url\"}) by (url)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "HTTP Duration (phase = $phase)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{job=\"$job\",url=~\"$url\", phase=~\"$phase\"}",
     "legendFormat": "{{url}} - {{ phase }}"
    }
   ]
  },
  {
   "title": "TLS version",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "probe_tls_version_info{job=\"$job\",url=~\"$url\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{job=\"$job\",url=~\"$url\"} - time()",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{job=\"$job\",url=~\"$url\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Status over Time",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "status"
    }
   ]
  },
  {
   "title": "DNS Resolution from dc1 over Time",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "probe_dns_query_succeeded{job=\"blackbox_server1_rest_api\",instance=\"$instance\",dnsserver=\"10.10.10.10\"}",
     "legendFormat": "status"
    }
   ]
  },
  {
   "title": "DNS Resolution from dc2 over Time",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "probe_dns_query_succeeded{job=\"blackbox_server1_rest_api\", instance=\"$instance\",dnsserver=\"10.10.10.11\"}",
     "legendFormat": "status"
    }
   ]
  }
 ]
}